import { Student } from "./types/student.ts";

export const DefaultData: Student[] = [
    {
        fish: 'dsdadad sadas',
        birthDate: '2001.25.03',
        location: 'andijon',
        passportNumber: 'AB74545',
        phoneNumber: '45456456456',
        eduDir: 'ekonom',
        course: 'matem',
        group: '654-19',
        father: '',
        mother: '',
    },
    {
        fish: 'cgcvbb sadas',
        birthDate: '2001.25.03',
        location: 'andijon',
        passportNumber: 'AB74545',
        phoneNumber: '45456456456',
        eduDir: 'ekonom',
        course: 'matem',
        group: '654-19',
        father: 'adsdad asdasd',
        mother: 'dsadasd  dasd a',
    },
    {
        fish: 'asdasdasd sadas',
        birthDate: '2001.25.03',
        location: 'andijon',
        passportNumber: 'AB74545',
        phoneNumber: '45456456456',
        eduDir: 'ekonom',
        course: 'matem',
        group: '654-19',
        father: 'adsdad asdasd',
        mother: 'dsadasd  dasd a',
    },
    {
        fish: '5454545 sadas',
        birthDate: '2001.25.03',
        location: 'andijon',
        passportNumber: 'AB74545',
        phoneNumber: '45456456456',
        eduDir: 'ekonom',
        course: 'matem',
        group: '654-19',
        father: 'adsdad asdasd',
        mother: 'dsadasd  dasd a',
    },
];